# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
""

Fixtures.create(club_name: "Example 1", club_info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sagittis ullamcorper est. Vestibulum dignissim lacus eget erat tempus commodo. Curabitur ut diam eget magna luctus malesuada. Fusce eros dui, consequat a lectus ut, elementum varius ipsum. Donec id dapibus ex. Mauris vel ultrices eros. Nulla eleifend iaculis orci, vel dapibus sapien egestas tristique. Sed ornare sed est quis ornare. Ut vitae turpis sed orci maximus placerat sit amet sed dui", address: "123 Anywhere", city: "Chicago", providence: "Illinois", country: "usa", club_email: "example@test.com", age: "12-16", club_twitter: "@example", club_website: "www.example.com")
Fixtures.create(club_name: "Example 2", club_info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sagittis ullamcorper est. Vestibulum dignissim lacus eget erat tempus commodo. Curabitur ut diam eget magna luctus malesuada. Fusce eros dui, consequat a lectus ut, elementum varius ipsum. Donec id dapibus ex. Mauris vel ultrices eros. Nulla eleifend iaculis orci, vel dapibus sapien egestas tristique. Sed ornare sed est quis ornare. Ut vitae turpis sed orci maximus placerat sit amet sed dui", address: "123 Anywhere", city: "Chicago", providence: "Illinois", country: "usa", club_email: "example@test.com", age: "12-16", club_twitter: "@example", club_website: "www.example.com")
Fixtures.create(club_name: "Example 3", club_info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sagittis ullamcorper est. Vestibulum dignissim lacus eget erat tempus commodo. Curabitur ut diam eget magna luctus malesuada. Fusce eros dui, consequat a lectus ut, elementum varius ipsum. Donec id dapibus ex. Mauris vel ultrices eros. Nulla eleifend iaculis orci, vel dapibus sapien egestas tristique. Sed ornare sed est quis ornare. Ut vitae turpis sed orci maximus placerat sit amet sed dui", address: "123 Anywhere", city: "Chicago", providence: "Illinois", country: "usa", club_email: "example@test.com", age: "12-16", club_twitter: "@example", club_website: "www.example.com")
Fixtures.create(club_name: "Example 4", club_info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sagittis ullamcorper est. Vestibulum dignissim lacus eget erat tempus commodo. Curabitur ut diam eget magna luctus malesuada. Fusce eros dui, consequat a lectus ut, elementum varius ipsum. Donec id dapibus ex. Mauris vel ultrices eros. Nulla eleifend iaculis orci, vel dapibus sapien egestas tristique. Sed ornare sed est quis ornare. Ut vitae turpis sed orci maximus placerat sit amet sed dui", address: "123 Anywhere", city: "Chicago", providence: "Illinois", country: "usa", club_email: "example@test.com", age: "12-16", club_twitter: "@example", club_website: "www.example.com")
Fixtures.create(club_name: "Example 5", club_info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sagittis ullamcorper est. Vestibulum dignissim lacus eget erat tempus commodo. Curabitur ut diam eget magna luctus malesuada. Fusce eros dui, consequat a lectus ut, elementum varius ipsum. Donec id dapibus ex. Mauris vel ultrices eros. Nulla eleifend iaculis orci, vel dapibus sapien egestas tristique. Sed ornare sed est quis ornare. Ut vitae turpis sed orci maximus placerat sit amet sed dui", address: "123 Anywhere", city: "Chicago", providence: "Illinois", country: "usa", club_email: "example@test.com", age: "12-16", club_twitter: "@example", club_website: "www.example.com")
Fixtures.create(club_name: "Example 6", club_info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sagittis ullamcorper est. Vestibulum dignissim lacus eget erat tempus commodo. Curabitur ut diam eget magna luctus malesuada. Fusce eros dui, consequat a lectus ut, elementum varius ipsum. Donec id dapibus ex. Mauris vel ultrices eros. Nulla eleifend iaculis orci, vel dapibus sapien egestas tristique. Sed ornare sed est quis ornare. Ut vitae turpis sed orci maximus placerat sit amet sed dui", address: "123 Anywhere", city: "Chicago", providence: "Illinois", country: "usa", club_email: "example@test.com", age: "12-16", club_twitter: "@example", club_website: "www.example.com")
Fixtures.create(club_name: "Example 7", club_info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sagittis ullamcorper est. Vestibulum dignissim lacus eget erat tempus commodo. Curabitur ut diam eget magna luctus malesuada. Fusce eros dui, consequat a lectus ut, elementum varius ipsum. Donec id dapibus ex. Mauris vel ultrices eros. Nulla eleifend iaculis orci, vel dapibus sapien egestas tristique. Sed ornare sed est quis ornare. Ut vitae turpis sed orci maximus placerat sit amet sed dui", address: "123 Anywhere", city: "Chicago", providence: "Illinois", country: "usa", club_email: "example@test.com", age: "12-16", club_twitter: "@example", club_website: "www.example.com")
Fixtures.create(club_name: "Example 8", club_info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sagittis ullamcorper est. Vestibulum dignissim lacus eget erat tempus commodo. Curabitur ut diam eget magna luctus malesuada. Fusce eros dui, consequat a lectus ut, elementum varius ipsum. Donec id dapibus ex. Mauris vel ultrices eros. Nulla eleifend iaculis orci, vel dapibus sapien egestas tristique. Sed ornare sed est quis ornare. Ut vitae turpis sed orci maximus placerat sit amet sed dui", address: "123 Anywhere", city: "Chicago", providence: "Illinois", country: "usa", club_email: "example@test.com", age: "12-16", club_twitter: "@example", club_website: "www.example.com")


